# This is a basic workflow to help you get started with Actions

name: NoiseAware Android deploy 

# Controls when the workflow will run
# on:
#   push:
#     tags:
#     - 'v*'
# on:
#   push:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      # Check code
      - name: Checkout the code
        uses: actions/checkout@v2

      # Setup java
      - name: Setup Java to compile Android project
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Install and set Flutter version
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
          channel: 'stable'

      # Create the Keystore
      - name: Create the Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          # import keystore from secrets
          echo $KEYSTORE_BASE64 | base64 -d > $RUNNER_TEMP/my_production.keystore

      # Flutter part
      - name: Restore packages
        run: flutter pub get

      - name: Build Flutter
        run: flutter build appbundle --release

      #  # Xcode part
      # - name: Build resolve Swift dependencies
      #   run: xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release

      # - name: Build xArchive
      #   run: |
      #     xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release DEVELOPMENT_TEAM=86Y67F9SF6 -sdk 'iphoneos' -destination 'generic/platform=iOS' -archivePath build-output/app.xcarchive PROVISIONING_PROFILE=a97d83e9-8ded-4ca9-8992-95b4cf035148 clean archive CODE_SIGN_IDENTITY="Apple Distribution: Sigh LLC (86Y67F9SF6)"
      
      # - name: Export ipa
      #   run: xcodebuild -exportArchive -archivePath build-output/app.xcarchive -exportPath build-output/ios -exportOptionsPlist ios/ExportOptions.plist
      
      # - name: Publish iOS Artefacts
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: release-ios
      #     path: build-output/ios